### ISSUE TITLE
Bug `OverrideProcessPurchase'

### ISSUE THREAD

**Issue by Lbstudio-159** [suriyun-production/shooter-io-docs#1]
Assets/ShooterIO/Monetization/Scripts/MonetizationManager.cs(393,13): error CS0103: The name `OverrideProcessPurchase' does not exist in the current context

**Comment by insthync** [comment]
[ShooterIO_Monetization.zip](https://github.com/suriyun-production/shooter-io-docs/files/3732899/ShooterIO_Monetization.zip)
Try import this package and add `UNITY_PURCHASING` to **Scripting Define Symbols**, So it will be
```
PHOTON_UNITY_NETWORKING;PUN_2_0_OR_NEWER;PUN_2_OR_NEWER;UNITY_PURCHASING
```
