### ISSUE TITLE
Suddenly Weapons not showing up in Weapons window in home scene.

### ISSUE THREAD

**Issue by pandey623** [suriyun-production/shooter-io-docs#10]
![Screenshot_20191122-073358](https://user-images.githubusercontent.com/25692596/69392248-6d66ce00-0cfb-11ea-99cb-bdfb44586bf8.png)

**Comment by insthync** [comment]
Is there any error?, Did you set weapons ?

![Screenshot_183](https://user-images.githubusercontent.com/2697550/69392794-c50c3600-0d09-11ea-928d-61de54989463.png)

**Comment by pandey623** [comment]
Its already attached.
![Capture1](https://user-images.githubusercontent.com/25692596/69396080-2252b800-0d07-11ea-929c-240d3edae4b5.PNG)

**Comment by insthync** [comment]
No errors ?

**Comment by pandey623** [comment]
No errors.
I am going to share with you the steps to reproduce the issue.
Steps:
Install the Shooter IO game. purchase any item from item panel.
After this clear the data or reinstall the game.
Now again check the game, It will not show anything in weapon section.
But if i again purchase the same item(earlier purchased item) or any other item from item panel. 
Everything will show up normally. 

The issue with body and head data as well. I was having 5 body before clearing the data. Then again I reinstall or clear the data It was showing 2 bodies and But if i again purchase the same item(earlier purchased item) or any other item from item panel. 
Everything will show up normally. Now it will show 5 bodies which was originally I purchased in previous install of the game.

**Comment by insthync** [comment]
You tested on Android devices, right ?

**Comment by insthync** [comment]
That's normal, Unity's PlayerPrefs will be removed when uninstall and install again, If you want to implement online save you should try Playfab integration https://github.com/insthync/dot-io-playfab-client

**Comment by pandey623** [comment]
> You tested on Android devices, right ?

Yes I tested on android device.

**Comment by pandey623** [comment]
> That's normal, Unity's PlayerPrefs will be removed when uninstall and install again, If you want to implement online save you should try Playfab integration https://github.com/insthync/dot-io-playfab-client

But why body and head is showing 2/2 each but no weapons are showing at all. If that is the case of saving then Body and head should also be 0/0 by default or What ever is the default value(set 2 body and 2 head in game instance). Because Weapons are already set by default in game Instance alongwith body and head. and why it is the case for only weapons. I hope I have made my point clear. I think by resetting after reinstall is not working in weapons case.

**Comment by pandey623** [comment]
> That's normal, Unity's PlayerPrefs will be removed when uninstall and install again, If you want to implement online save you should try Playfab integration https://github.com/insthync/dot-io-playfab-client

**Comment by insthync** [comment]
I tried to reproduce, but does not found the issues, can you send me your build ?

**Comment by pandey623** [comment]
Here is the apk file : 
https://drive.google.com/open?id=1pxsiOvP7tq8BL6IL4uehg2-NTJa5JTKr

**Comment by insthync** [comment]
I found an errors, you don't see it in editor ?, I can't see which line is the cause of problems by logcat. So I have to guess where the problems occurs

![Screenshot_188](https://user-images.githubusercontent.com/2697550/69479081-0e54a680-0e2c-11ea-83df-251b4b222eb0.png)

**Comment by insthync** [comment]
Please capture screen shot of `GameInstance.cs` source codes from line 29 to 100 ?

**Comment by pandey623** [comment]
![Capture2](https://user-images.githubusercontent.com/25692596/69479492-d34e7500-0e23-11ea-8370-cf6fd1056589.PNG)
![Capture3](https://user-images.githubusercontent.com/25692596/69479493-d3e70b80-0e23-11ea-9da1-6db2be153dbf.PNG)

**Comment by insthync** [comment]
Okay, try this package

[ShooterIOFixInvalidLifeCycle.zip](https://github.com/suriyun-production/shooter-io-docs/files/3882567/ShooterIOFixInvalidLifeCycle.zip)

**Comment by insthync** [comment]
If this is work, it could fix Bomber IO issues too.

**Comment by pandey623** [comment]
Here is the another build apk file after importing your changes.
Now by default weapons are showing up normally alongwith body and head. But When I am purchasing machinegun. It is reflected in weapon screen panel. When I again open Item list All the items inside item list including bodies are showing purchased. I didn't purchased those bodies. Now they are not intractable and not even showing up in bodies panel count.
Please have a look at this. 
https://drive.google.com/open?id=1GlljhfHHnSDk9RM-EwGPEWWnfHcGR8b6

**Comment by insthync** [comment]
I think that's because you have not enough gold :P

**Comment by pandey623** [comment]
I checked in the game I was having 200 Gold coins but still nothing is interactable
![Screenshot_20191124-165109](https://user-images.githubusercontent.com/25692596/69493960-b4131e80-0edb-11ea-9a3c-485f12ad6ca0.png)
![Screenshot_20191124-165114](https://user-images.githubusercontent.com/25692596/69493961-b4131e80-0edb-11ea-8506-28164373153e.png)

.

**Comment by insthync** [comment]
Seems like you have to exit game then enter game again, I will fix it

**Comment by insthync** [comment]
Try this package

[MonetizationKeepUpdateUI.zip](https://github.com/suriyun-production/shooter-io-docs/files/3883697/MonetizationKeepUpdateUI.zip)

**Comment by pandey623** [comment]
Now It is working fine in build.
**Can you please do the same changes for bomber io as well.**
**One Feedback:**
Is it possible to differentiate (Items panel screen) which items are purchased and which are not, When there is no sufficient gold is present. Currently everything is changing to disabled state which is conflicting with what are purchased and what are not purchased.

**Comment by insthync** [comment]
You can try use `UI Item Unlock Activator` component to then you may set Unlocked text to `Activating While Unlock Objects` to make it visible while item is unlocked.
