### ISSUE TITLE
suggestion : loading scene 

### ISSUE THREAD

**Issue by polymahh** [suriyun-production/shooter-io-docs#13]
what i suggest is creating a loading scene , between home and map scenes , it seems like the match start as soon as the scene start loading and it takes a lot of resources to instantiate everything and the player has to move 
also moving the velocity update from fixedupdate if possible ' i tried but failed '

**Comment by polymahh** [comment]
i made the game a little bit faster at the start by pooling the bullets and effects and drops i used lean pool from the asset store . it is still a bit slow but acceptable maybe adding loading scene is going to help , here is the link from play store : https://play.google.com/store/apps/details?id=com.poly.royaleblast  
-the fixedupdate is the right place for velocity i was wrong about changing it.

**Comment by insthync** [comment]
Looking good :)
