### ISSUE TITLE
Shooter IO - Errors After PUN2 updated code (11.04.2020)

### ISSUE THREAD

**Issue by ximishe** [suriyun-production/shooter-io-docs#15]
Hello i got some errors with Running this asset because of PUN2 got update.
Battle Royale - crashing client now
Battle Modes works but i got that bugs:

NullReferenceException: Object reference not set to an instance of an object
UIPhotonWaitingRoom.UpdateRoomData () (at Assets/ShooterIO/SimplePhoton2NetworkManager/Scripts/UI/UIPhotonWaitingRoom.cs:85)
UIPhotonWaitingRoom.OnCustomRoomPropertiesChangedCallback (ExitGames.Client.Photon.Hashtable propertiesThatChanged) (at Assets/ShooterIO/SimplePhoton2NetworkManager/Scripts/UI/UIPhotonWaitingRoom.cs:353)
SimplePhotonNetworkManager.OnRoomPropertiesUpdate (ExitGames.Client.Photon.Hashtable propertiesThatChanged) (at Assets/ShooterIO/SimplePhoton2NetworkManager/Scripts/Network/SimplePhotonNetworkManager.cs:631)
Photon.Realtime.InRoomCallbacksContainer.OnRoomPropertiesUpdate (ExitGames.Client.Photon.Hashtable propertiesThatChanged) (at Assets/Photon/PhotonRealtime/Code/LoadBalancingClient.cs:3858)
Photon.Realtime.LoadBalancingClient.ReadoutProperties (ExitGames.Client.Photon.Hashtable gameProperties, ExitGames.Client.Photon.Hashtable actorProperties, System.Int32 targetActorNr) (at Assets/Photon/PhotonRealtime/Code/LoadBalancingClient.cs:1982)
Photon.Realtime.LoadBalancingClient.OnEvent (ExitGames.Client.Photon.EventData photonEvent) (at Assets/Photon/PhotonRealtime/Code/LoadBalancingClient.cs:2954)
ExitGames.Client.Photon.PeerBase.DeserializeMessageAndCallback (ExitGames.Client.Photon.StreamBuffer stream) (at C:/Dev/photon-sdk-dotnet/PhotonDotNet/PeerBase.cs:663)
ExitGames.Client.Photon.EnetPeer.DispatchIncomingCommands () (at C:/Dev/photon-sdk-dotnet/PhotonDotNet/EnetPeer.cs:545)
ExitGames.Client.Photon.PhotonPeer.DispatchIncomingCommands () (at C:/Dev/photon-sdk-dotnet/PhotonDotNet/PhotonPeer.cs:1759)
Photon.Pun.PhotonHandler.Dispatch () (at Assets/Photon/PhotonUnityNetworking/Code/PhotonHandler.cs:205)
Photon.Pun.PhotonHandler.FixedUpdate () (at Assets/Photon/PhotonUnityNetworking/Code/PhotonHandler.cs:139)

Please Answer if u Wrote That. Thanks 👍

**Comment by insthync** [comment]
Yes, seems like they changes a lot, I'm going to fix it.

**Comment by ximishe** [comment]
Oh So Great!! :) Thank u

**Comment by insthync** [comment]
Update these packages:

[PhotonShooterIO_UpdatePUN2.zip](https://github.com/suriyun-production/shooter-io-docs/files/4474512/PhotonShooterIO_UpdatePUN2.zip)
