### ISSUE TITLE
Errors after impoting the latest version in fresh project from asset store.

### ISSUE THREAD

**Issue by pandey623** [suriyun-production/shooter-io-docs#16]
I imported the latest asset package in fresh project from the Asset store.
Then imported the photon pun2 from assets tore.
Then enabled IAP.
When I run the game It is throwing errors.

Errors:

Assembly 'Library/ScriptAssemblies/Assembly-CSharp-firstpass.dll' will not be loaded due to errors:
Reference has errors 'Stores'.

Assembly 'Library/ScriptAssemblies/Assembly-CSharp-Editor-firstpass.dll' will not be loaded due to errors:
Reference has errors 'Assembly-CSharp-firstpass'.

Assembly 'Library/ScriptAssemblies/Assembly-CSharp-Editor.dll' will not be loaded due to errors:
Reference has errors 'Stores'.

Assembly 'Assets/Plugins/UnityPurchasing/Bin/Editor.dll' will not be loaded due to errors:
Unable to resolve reference 'UDP'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.

Assembly 'Assets/Plugins/UnityPurchasing/Bin/Stores.dll' will not be loaded due to errors:
Unable to resolve reference 'UDP'. Is the assembly missing or incompatible with the current platform?
Reference validation can be disabled in the Plugin Inspector.

Exception thrown while invoking [DidReloadScripts] method 'Photon.Pun.PhotonEditor:OnDidReloadScripts ()' : FileNotFoundException: Could not load file or assembly 'Stores, Version=1.0.7268.24524, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
System.Reflection.MonoMethodInfo.GetMethodInfo (System.IntPtr handle) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Reflection.MonoMethod.GetPseudoCustomAttributes () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.MonoCustomAttrs.GetPseudoCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.MonoCustomAttrs.IsDefined (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Reflection.MonoMethod.IsDefined (System.Type attributeType, System.Boolean inherit) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Photon.Pun.PhotonEditor+<>c.<UpdateRpcList>b__48_3 (System.Reflection.MethodInfo m) (at Assets/Photon/PhotonUnityNetworking/Code/Editor/PhotonEditor.cs:706)
System.Linq.Enumerable+WhereSelectEnumerableIterator`2[TSource,TResult].ToArray () (at <fbb5ed17eb6e46c680000f8910ebb50c>:0)
System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <fbb5ed17eb6e46c680000f8910ebb50c>:0)
Photon.Pun.PhotonEditor.UpdateRpcList () (at Assets/Photon/PhotonUnityNetworking/Code/Editor/PhotonEditor.cs:706)
Photon.Pun.PhotonEditor.OnDidReloadScripts () (at Assets/Photon/PhotonUnityNetworking/Code/Editor/PhotonEditor.cs:191)

FileNotFoundException: Could not load file or assembly 'Stores, Version=1.0.7268.24524, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
System.Reflection.MonoMethodInfo.GetMethodInfo (System.IntPtr handle) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Reflection.MonoMethod.GetPseudoCustomAttributes () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.MonoCustomAttrs.GetPseudoCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.MonoCustomAttrs.IsDefined (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Reflection.MonoMethod.IsDefined (System.Type attributeType, System.Boolean inherit) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Photon.Pun.PhotonEditor+<>c.<UpdateRpcList>b__48_3 (System.Reflection.MethodInfo m) (at Assets/Photon/PhotonUnityNetworking/Code/Editor/PhotonEditor.cs:706)
System.Linq.Enumerable+WhereSelectEnumerableIterator`2[TSource,TResult].ToArray () (at <fbb5ed17eb6e46c680000f8910ebb50c>:0)
System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <fbb5ed17eb6e46c680000f8910ebb50c>:0)
Photon.Pun.PhotonEditor.UpdateRpcList () (at Assets/Photon/PhotonUnityNetworking/Code/Editor/PhotonEditor.cs:706)
Photon.Pun.PhotonEditor.OnInitialHierarchyChanged () (at Assets/Photon/PhotonUnityNetworking/Code/Editor/PhotonEditor.cs:202)
UnityEditor.EditorApplication.Internal_CallHierarchyHasChanged () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:231)

KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
UIMainMenu.UpdateWeapon () (at Assets/ShooterIO/Scripts/UI/UIMainMenu.cs:159)
UIMainMenu.Update () (at Assets/ShooterIO/Scripts/UI/UIMainMenu.cs:122)

**Comment by insthync** [comment]
I think this were fixed, so I will close it.
