### ISSUE TITLE
Ads is not working (Solved)

### ISSUE THREAD

**Issue by kevin2562001** [suriyun-production/shooter-io-docs#18]
I followed the shooter IO tutorial to set up the ads in service, but it doesn't work even I changed to Android platform. It shows ads is not enabled or not support the platform.

Then I find this in official website and follow the setup.
https://unityads.unity3d.com/help/unity/integration-guide-unity#implementing-rewarded-ads

After that, it gave me a list of error
![image](https://user-images.githubusercontent.com/10719488/90408549-8cec2500-e0da-11ea-9135-b8e8ddadb26f.png)

How can I fix it and what version of unity should I use?

Current version:
Unity: 2019.4.5f1
Shooter IO Pun2: latest

**Comment by insthync** [comment]
Try remove UnityAds from Assets folder and also remove sample ads banner from Editor/Resource

Then install Advertisement package via package manager

![Screenshot_17](https://user-images.githubusercontent.com/2697550/90573201-0e79ab00-e1e0-11ea-8d38-b17be06c3444.png)

And add `UNITY_PURCHASING`, `UNITY_ADS` to scripting define symbol

![Screenshot_16](https://user-images.githubusercontent.com/2697550/90573239-281af280-e1e0-11ea-8697-f3455b683f19.png)

**Comment by kevin2562001** [comment]
The ads error is gone, but the ads button is still not allow to click, the test mode is checked in service.

![image](https://user-images.githubusercontent.com/10719488/90608559-6098eb80-e235-11ea-99b9-ce043d8f7e41.png)
![image](https://user-images.githubusercontent.com/10719488/90608655-82926e00-e235-11ea-976e-df9e5e9e90ba.png)
![image](https://user-images.githubusercontent.com/10719488/90608488-4ced8500-e235-11ea-8d02-6f5b7543c98c.png)
![image](https://user-images.githubusercontent.com/10719488/90608507-54ad2980-e235-11ea-99fd-994d99bad4cd.png)
![image](https://user-images.githubusercontent.com/10719488/90608533-5a0a7400-e235-11ea-95f0-6ee41bba4b92.png)

**Comment by kevin2562001** [comment]
It works now, thank you
