### ISSUE TITLE
IAP Shop not work

### ISSUE THREAD

**Issue by kevin2562001** [suriyun-production/shooter-io-docs#19]
I followed this guide to setup Iap product
https://suriyun-production.github.io/shooter-io-docs/#/pages/012-_Shooter-IO---Monetization--In-Game-Packages--IAP-Products?id=how-to-add-iap-product-data

When I try to buy the item, it shows this error
![image](https://user-images.githubusercontent.com/10719488/90855547-7aac0880-e3b2-11ea-8c07-50043f5b9b11.png)

Other info:
IAP product
![image](https://user-images.githubusercontent.com/10719488/90855594-91525f80-e3b2-11ea-98b3-4712ab7d5b24.png)

IAP Catalog
![image](https://user-images.githubusercontent.com/10719488/90856297-37eb3000-e3b4-11ea-9daa-58a8cda1113b.png)

**Comment by insthync** [comment]
Don't test IAP in editor, you have to build and test on device, try build for android internal testing first.

**Comment by kevin2562001** [comment]
It works now, updated to latest version and switch to android platform
