### ISSUE TITLE
Lack   can not find

### ISSUE THREAD

**Issue by WwwStackOverflow** [suriyun-production/shooter-io-docs#2]
The type or namespace name `Photon' could not be found
The type or namespace name `PunBehaviour' could not be found
 The type or namespace name `ExitGames' could not be found.
 The type or namespace name `PunBehaviour' could not be found.
The type or namespace name `PhotonPlayer' could not be found.
....

**Comment by insthync** [comment]
Did you imported PUN2 package? https://assetstore.unity.com/packages/tools/network/pun-2-free-119922
