### ISSUE TITLE
Error when npc is taking items

### ISSUE THREAD

**Issue by kevin2562001** [suriyun-production/shooter-io-docs#20]
I just try to test play the "Battle" scenes with IO mode without making any changes, when the AI walk through the items, it shows error message in console. The AI won't fire any weapon, but they can still use dash and aim to the player.

When second player joined the game, client will see the host movement looks laggy even the walk animation.

![image](https://user-images.githubusercontent.com/10719488/90858052-f78db100-e3b7-11ea-84ca-4530b6b049d3.png)

Unity 2019.4.5f1
Photon2: latest (last check 21/8/2020)
Shooter IO: latest (last check 21/8/2020)

**Comment by insthync** [comment]
Fixed some time ago
