### ISSUE TITLE
What command is to set 'Game Match Time', 'Game Max Kill Count' when starting the Dedicated Server App?

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/shooter-io-docs#22]
What command is to set 'Game Match Time', 'Game Max Kill Count' when starting the Dedicated Server App?

I tried -gameMatchTime 180 -gameMaxKill 20
but it is not working, please help me now. Thanks in advance!

**Comment by insthync** [comment]
For now there are following commands:
-gameServerStart
-gameServerPort
-gameMaxConnections
-gameOnlineScene
-gameRule
-gameBotCount

There is no commands for those options yet, you have to set it at  `GameRule` data, may try find (IO, DeathMatch, BattleRoyale in editor) or wait for the next version.

**Comment by isaanyoha** [comment]
Ok. So when is the next version coming?

**Comment by insthync** [comment]
[ShooterIO-ReadArgsPatch.zip](https://github.com/suriyun-production/shooter-io-docs/files/5779610/ShooterIO-ReadArgsPatch.zip)

Import this patch, there are new args:
```
-gameBotCount
-gameMatchTime
-gameMatchKill
-gameMatchScore
```

**Comment by isaanyoha** [comment]
I imported the patch, add the new args on starting the dedicated server but I do not see the gameMatchTime counting down for Death Match and no kill count. Only IO seems to be working correctly for dedicated server. It is suppose to show a count down  timer which ends the game and increment your kill count by 1 when you kill & show list of players & kills at the game end. It works correctly on LAN. Are my doing anything wrong? (Below is my target). 

C:\ShooterIO1\ShooterIO1.exe -gameServerStart -gameServerPort 7700 -gameMaxConnections 50 -gameRule DeathMatchNetworkGameRule -gameBotCount 2 -gameOnlineScene "Battle" -gameMatchTime 180 -gameMatchKill 20 -gameMatchScore 20

Please assist me, urgently

**Comment by insthync** [comment]
[ShooterIO-FixWrongGameplayRule.zip](https://github.com/suriyun-production/shooter-io-docs/files/5822324/ShooterIO-FixWrongGameplayRule.zip)
Import this to fix issues

**Comment by isaanyoha** [comment]
> [ShooterIO-FixWrongGameplayRule.zip](https://github.com/suriyun-production/shooter-io-docs/files/5822324/ShooterIO-FixWrongGameplayRule.zip)
> Import this to fix issues

Let me try it out and get back to you as soon as possible. Thanks for your flash responds! I really appreciate

**Comment by isaanyoha** [comment]
![Capture8](https://user-images.githubusercontent.com/4920405/104766107-4a527580-576a-11eb-9d76-18b6d0edc7c4.PNG)
After downloading and installing the patch, and run the server, I click on the 'ONLINE' button and it immediately shows up the list of players and their kills and without allowing me to play the game. I notice that as the list is still in front of me and not allowing me to play, the list gets updated as the bots keep killing in the background

**Comment by isaanyoha** [comment]
This list shows up while the time has not elapsed yet and it can't allow me to even play because when I hit on exit, it takes me to home (Below is my Target)

C:\ShooterIO1\ShooterIO1.exe -gameServerStart -gameServerPort 7700 -gameMaxConnections 50 -gameRule DeathMatchNetworkGameRule -gameBotCount 2 -gameOnlineScene "Battle" -gameMatchTime 180 -gameMatchKill 30 -gameMatchScore 30

**Comment by insthync** [comment]
Send your invoice id to my email: ittipon.bay@gmail.com I will send full update package.

**Comment by isaanyoha** [comment]
Ok. I will do that right now

**Comment by isaanyoha** [comment]
Sent to email: ittipon.bay@gmail.com now

**Comment by isaanyoha** [comment]
Ok, Got the mail. Let me try it out and get back to you as soon as possible. Thanks Suriyun!

**Comment by isaanyoha** [comment]
Nice one. It works now, Thank you so much!

**Comment by isaanyoha** [comment]
When the game finishes and the list of kill count shows up and when I click on the 'exit' button of the list it and it takes me to home. And then when I restart the server and go back to the client and click on the ONLINE button, it shows the list like the issue it used to have when it does not allow me to play. It is until I stop the client and restart it again then it takes me in with the accurate game state. Please assist me
