### ISSUE TITLE
How To Make Camera Follow Player Rotation

### ISSUE THREAD

**Issue by isaanyoha** [suriyun-production/shooter-io-docs#23]
How To Make Camera Follow Player Rotation

**Comment by insthync** [comment]
You will have to change how to rotate character controls codes in `CharacterEntity.cs` in `UpdateInput` function.
And in camera, there is a `FollowCamera` component which you can tick on `Use Target Y Rotation` to make it rotate follow character's rotation

**Comment by isaanyoha** [comment]
Ok, Thanks!
