### ISSUE TITLE
characters and items fail to sync correctly again

### ISSUE THREAD

**Issue by kevin2562001** [suriyun-production/shooter-io-docs#26]
I was using a older version of this for my project, I remember there was the same syncing problem but somehow it was fixed.

Recently I tried the latest version from a clean project, the photon syncing isn't work well. All characters and items local different position and rotation in their window.
Both Pun2 and Shooter-IO are the latest version.

To reproduce the problem:
just build the game and create a room with more than one player, then the problem will be shown in both windows.

**Comment by insthync** [comment]
As I try, It still looks fine for me, not sure which component you use for transform syncing, mine is `Photon Transform View Classic`

![Screenshot_377](https://user-images.githubusercontent.com/2697550/115163957-584fc380-a0d6-11eb-831d-21037f14b94c.png)

**Comment by insthync** [comment]
![Screenshot_378](https://user-images.githubusercontent.com/2697550/115164437-8fbe7000-a0d6-11eb-8a6f-c2c7583c439d.png)

**Comment by kevin2562001** [comment]
After I reimport PUN2, it works again.
Look like PUN2 has some problem son it, now my new project is working, everything is syncing perfectly.

**Comment by kevin2562001** [comment]
At the end I found out if anything doesn't work, try to clear and update the RPC.
Not sure why but it just works
