### ISSUE TITLE
Can't find any Playfab integration?

### ISSUE THREAD

**Issue by Whiskah** [suriyun-production/shooter-io-docs#29]
On the store page for this it states "Playfab integration" but the only thing I can see here filewise in the project is "Playfabclientdemo" is this all I am expecting to see etc? Was looking to add in google login through playfab etc.
There is also nothing in the online guide provided showing anything to do with playfab.

************** Ignore everything I just said as I found it right here on the github *****************

**Comment by insthync** [comment]
Okay, so you found it?, then I will close this.
