### ISSUE TITLE
hello. on version 2019.1.14 an error occurs

### ISSUE THREAD

**Issue by Lbstudio-159** [suriyun-production/shooter-io-docs#3]
hello. on version 2019.1.14 an error occurs

Assets\ShooterIO\Monetization\Editor\IapProductDataEditor.cs(35,23): error CS0103: The name 'ProductCatalog' does not exist in the current context

Assets\ShooterIO\Monetization\Editor\IapProductDataEditor.cs(57,13): error CS0103: The name 'ProductCatalogEditor' does not exist in the current context

**Comment by insthync** [comment]
You have to turn on Unity Purchasing https://docs.unity3d.com/Manual/UnityIAPSettingUp.html

**Comment by Lbstudio-159** [comment]
yes. 
https://pastenow.ru/715475a3334baa8d2d3eb7c3a5a2f14b

**Comment by insthync** [comment]
Try update your IAP package following these steps https://medium.com/suriyun-production/how-to-update-unity-iap-aa192608ded2
