### ISSUE TITLE
Errors after imporitng Shooter IO (litenet version)

### ISSUE THREAD

**Issue by JurajHusek** [suriyun-production/shooter-io-docs#32]
Hello,
I bought https://assetstore.unity.com/packages/templates/systems/shooter-io-104584#description pack and after importing it to Unity, I got these two errors:

Assets\ShooterIO\LiteNetLibManager\Plugins\ZLogger\IAsyncLogProcessor.cs(7,43): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Assets\ShooterIO\LiteNetLibManager\Plugins\ZLogger\AsyncStreamLineMessageWriter.cs(12,69): error CS0433: The type 'IAsyncDisposable' exists in both 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

I would be very grateful for some fix as soon as possible,
thank you,
Juraj Hušek

**Comment by insthync** [comment]
Try do following this https://suriyun-production.github.io/mmorpg-kit-docs/#/pages/151-working-with-2021

**Comment by JurajHusek** [comment]
Works perfectly, thank you very much
