### ISSUE TITLE
Bots not having guns in hand to attack after updating the asset to the latest.

### ISSUE THREAD

**Issue by pandey623** [suriyun-production/shooter-io-docs#4]

**Comment by insthync** [comment]
Which version of package PUN2 or UNET ?

**Comment by pandey623** [comment]
PUN2

**Comment by insthync** [comment]
When did you update the package, before 8 Nov ?, As I tested on PC and Android, it's still working well.

**Comment by pandey623** [comment]
Yes I updated to the latest package from asset store.
I checked it in fresh project as well. When I am running battleroyale mode while creating game. I am recieving these errors.

NullReferenceException: Object reference not set to an instance of an object
IONetworkGameRule.GetStartWeapons () (at Assets/ShooterIO/Scripts/Network/IONetworkGameRule.cs:26)
IONetworkGameRule.NewPlayer (CharacterEntity character, System.Int32 selectHead, System.Int32 selectCharacter, System.Int32[] selectWeapons, System.Int32[] selectCustomEquipments, System.String extra) (at Assets/ShooterIO/Scripts/Network/IONetworkGameRule.cs:58)
CharacterEntity.RpcServerInit (System.Int32 selectHead, System.Int32 selectCharacter, System.Int32[] selectWeapons, System.Int32[] selectCustomEquipments, System.String extra) (at Assets/ShooterIO/Scripts/GamePlay/CharacterEntity.cs:1302)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Photon.Pun.PhotonNetwork.ExecuteRpc (ExitGames.Client.Photon.Hashtable rpcData, Photon.Realtime.Player sender) (at Assets/Photon/PhotonUnityNetworking/Code/PhotonNetworkPart.cs:472)
Photon.Pun.PhotonNetwork.RPC (Photon.Pun.PhotonView view, System.String methodName, Photon.Pun.RpcTarget target, Photon.Realtime.Player player, System.Boolean encrypt, System.Object[] parameters) (at Assets/Photon/PhotonUnityNetworking/Code/PhotonNetworkPart.cs:1102)
Photon.Pun.PhotonNetwork.RPC (Photon.Pun.PhotonView view, System.String methodName, Photon.Pun.RpcTarget target, System.Boolean encrypt, System.Object[] parameters) (at Assets/Photon/PhotonUnityNetworking/Code/PhotonNetwork.cs:2779)
Photon.Pun.PhotonView.RPC (System.String methodName, Photon.Pun.RpcTarget target, System.Object[] parameters) (at Assets/Photon/PhotonUnityNetworking/Code/PhotonView.cs:411)
CharacterEntity.CmdInit (System.Int32 selectHead, System.Int32 selectCharacter, System.Int32[] selectWeapons, System.Int32[] selectCustomEquipments, System.String extra) (at Assets/ShooterIO/Scripts/GamePlay/CharacterEntity.cs:1287)
GameNetworkManager.RpcAddPlayer () (at Assets/ShooterIO/Scripts/Network/GameNetworkManager.cs:63)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Photon.Pun.PhotonNetwork.ExecuteRpc (ExitGames.Client.Photon.Hashtable rpcData, Photon.Realtime.Player sender) (at Assets/Photon/PhotonUnityNetworking/Code/PhotonNetworkPart.cs:452)
Photon.Pun.PhotonNetwork.RPC (Photon.Pun.PhotonView view, System.String methodName, Photon.Pun.RpcTarget target, Photon.Realtime.Player player, System.Boolean encrypt, System.Object[] parameters) (at Assets/Photon/PhotonUnityNetworking/Code/PhotonNetworkPart.cs:1055)
Photon.Pun.PhotonNetwork.RPC (Photon.Pun.PhotonView view, System.String methodName, Photon.Realtime.Player targetPlayer, System.Boolean encrpyt, System.Object[] parameters) (at Assets/Photon/PhotonUnityNetworking/Code/PhotonNetwork.cs:2810)
Photon.Pun.PhotonView.RPC (System.String methodName, Photon.Realtime.Player targetPlayer, System.Object[] parameters) (at Assets/Photon/PhotonUnityNetworking/Code/PhotonView.cs:460)
SimplePhotonNetworkManager.RpcPlayerSceneChanged (System.String id) (at Assets/ShooterIO/SimplePhoton2NetworkManager/Scripts/Network/SimplePhotonNetworkManager.cs:704)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Photon.Pun.PhotonNetwork.ExecuteRpc (ExitGames.Client.Photon.Hashtable rpcData, Photon.Realtime.Player sender) (at Assets/Photon/PhotonUnityNetworking/Code/PhotonNetworkPart.cs:472)
Photon.Pun.PhotonNetwork.RPC (Photon.Pun.PhotonView view, System.String methodName, Photon.Pun.RpcTarget target, Photon.Realtime.Player player, System.Boolean encrypt, System.Object[] parameters) (at Assets/Photon/PhotonUnityNetworking/Code/PhotonNetworkPart.cs:1102)
Photon.Pun.PhotonNetwork.RPC (Photon.Pun.PhotonView view, System.String methodName, Photon.Pun.RpcTarget target, System.Boolean encrypt, System.Object[] parameters) (at Assets/Photon/PhotonUnityNetworking/Code/PhotonNetwork.cs:2779)
Photon.Pun.PhotonView.RPC (System.String methodName, Photon.Pun.RpcTarget target, System.Object[] parameters) (at Assets/Photon/PhotonUnityNetworking/Code/PhotonView.cs:411)
SimplePhotonNetworkManager+<OnSceneLoadedRoutine>d__110.MoveNext () (at Assets/ShooterIO/SimplePhoton2NetworkManager/Scripts/Network/SimplePhotonNetworkManager.cs:624)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

**Comment by pandey623** [comment]
Player and other players do not have gun in their hand. Game is getting too laggy and the above mentioned errors is showing up continously.

**Comment by insthync** [comment]
Try find `IONetworkGameRule` in `Project`, I want to see your `Start Weapons` settings 
![Screenshot_180](https://user-images.githubusercontent.com/2697550/69332683-c0a03880-0c89-11ea-91b1-02e0f7e9d2df.png)

**Comment by pandey623** [comment]
![Capture](https://user-images.githubusercontent.com/25692596/69343046-d36b3b00-0c92-11ea-9a18-f3ed19792dcc.PNG)

**Comment by insthync** [comment]
It's occurs on Battle Royale mode right ?

**Comment by insthync** [comment]
Try fix by this package

[FixNullStartWeapons.zip](https://github.com/suriyun-production/shooter-io-docs/files/3875236/FixNullStartWeapons.zip)

**Comment by pandey623** [comment]
Yes currently I found this issue in battle royale mode. I imported the fix you shared above, Now no error is coming.
