### ISSUE TITLE
Is it possible to add Admob ShowAd other than unity ShowAd in game scene on watch ad button.

### ISSUE THREAD

**Issue by pandey623** [suriyun-production/shooter-io-docs#6]
What is watch ad button?
What is it for? Will it do or add or reward something after watching ad?
What is the count in watch ad 2/2?
How i can remove the unity ads from my game and add admob ads in Home and Game scene.

**Comment by insthync** [comment]
I have made admob integration some time ago (https://github.com/insthync/unity-simple-monetization-admob) not sure it's still working or not, I will test it next week.

**Comment by pandey623** [comment]
ok, I request you to integrate Admob for WatchAd button as well inside Game Scene. The document for admob integration is for Home scene I suppose. I integrated it to my home scene, and it is working fine in Home scene. This will be helpful if you can integrate admob inside Game Scene as well where it is required. Like on WatchAd button after player is dead.

**Comment by insthync** [comment]
Both watch Ads to receive rewards and respawn are setup in home scene

**Comment by insthync** [comment]
Try setup like this 
![Screenshot_200](https://user-images.githubusercontent.com/2697550/69832924-6132c180-1263-11ea-973a-ea0fc6333f1c.png)
