### ISSUE TITLE
Google admob errors

### ISSUE THREAD

**Issue by Lbstudio-159** [suriyun-production/shooter-io-docs#7]
inity 2019.1.14
googlemobileads v.4.1.0
unity-simple-monetization-admob_v1.03

2 errors
1) Assets\GoogleMobileAds\Api\CustomNativeTemplateAd.cs(53,26): error CS0117: 'Utils' does not contain a definition for 'GetTexture2DFromByteArray'
2) Assets\GoogleMobileAds\Api\AdLoader.cs(42,19): error CS0117: 'Utils' does not contain a definition for 'CheckInitialization'

in GameInstance dont have google monitization manager!
screen shot https://yadi.sk/i/67ckQe7V7SWOpw

**Comment by insthync** [comment]
Okay, I will fix the package

**Comment by Lbstudio-159** [comment]
Hello. Will you fix this errors?

**Comment by insthync** [comment]
Wow, I said I will and I did. You have to update monetization package https://github.com/insthync/unity-simple-monetization
and 
https://github.com/insthync/unity-simple-monetization-admob
by download the source codes. because I didn't export from unity yet.

**Comment by Lbstudio-159** [comment]
Admob last version 1.3? Do you have unitypackage this 2 source code?

**Comment by insthync** [comment]
No unitypackage for latest code changes yet

**Comment by Lbstudio-159** [comment]
Вы будете делать, когда? Или дайте инструкцию как загрузить правильно данные исходные коды?

**Comment by Lbstudio-159** [comment]
Will you do when?  Or give instructions on how to download these source codes correctly?

**Comment by insthync** [comment]
[ShooterIO_Monetization.zip](https://github.com/suriyun-production/shooter-io-docs/files/3889683/ShooterIO_Monetization.zip)

**Comment by insthync** [comment]
And I just updated admob package https://github.com/insthync/unity-simple-monetization-admob/releases

**Comment by Lbstudio-159** [comment]
> And I just updated admob package https://github.com/insthync/unity-simple-monetization-admob/releases

hello. is not unitypackafe?

**Comment by insthync** [comment]
Updated https://github.com/insthync/unity-simple-monetization-admob/releases/tag/v1.04

**Comment by Lbstudio-159** [comment]
Admob is working, but with unity ads enabled, gradle error occurs during APK formation. disable unity ads in cervices, the APK is formed normally.
BUT unity ads show in APK! https://yadi.sk/d/ZXzJkRUlCylSiw

**Comment by insthync** [comment]
Try set `Ads Override Actions` like this
![Screenshot_197](https://user-images.githubusercontent.com/2697550/69831882-02b71480-125e-11ea-9923-68878a37c3ec.png)

**Comment by insthync** [comment]
In case that you don't know how to do it

![Screenshot_199](https://user-images.githubusercontent.com/2697550/69832864-1ca72600-1263-11ea-800d-6eba11baefe3.png)

![Screenshot_198](https://user-images.githubusercontent.com/2697550/69832871-20d34380-1263-11ea-85a1-e3a173583d25.png)

**Comment by Lbstudio-159** [comment]
Good afternoon. I hung the script on the button ( as it was in the previous instructions). exports in AdMob panels see, shows there is no. these two ways do not conflict with each other?

 the video (zip) shows the settings for advertising. you can also see that unity ads are called in respawn


[bandicam 2019-11-29 08-58-11-431.zip](https://github.com/suriyun-production/shooter-io-docs/files/3903320/bandicam.2019-11-29.08-58-11-431.zip)

![button-ads](https://user-images.githubusercontent.com/53878109/69836773-17a79e00-1286-11ea-8753-6e9f2839ec28.png)

**Comment by Lbstudio-159** [comment]
![define simbols](https://user-images.githubusercontent.com/53878109/69837150-66eece00-1288-11ea-9205-46824ff19f69.png)

**Comment by insthync** [comment]
Add `respawnPlacement` to ads override actions
![Screenshot_201](https://user-images.githubusercontent.com/2697550/69846301-2f8f1a00-12a6-11ea-9544-504c8777396a.png)

**Comment by Lbstudio-159** [comment]
on the button it is necessary to hang up the script?
![watch ads](https://user-images.githubusercontent.com/53878109/69848130-142b0b80-12b4-11ea-9fca-05d0d51458a3.png)

**Comment by insthync** [comment]
No, it's not.
And if you add `rewardedVideo` to `adsOverrideActions`, you actually can use `UIWatchAdsButton` component, does not have to change to `UIWatchAdmobRewardedVideoAdsButton`

**Comment by Lbstudio-159** [comment]
like this?
![show ads-new](https://user-images.githubusercontent.com/53878109/69849089-c06df180-12b6-11ea-98d5-3664573d93e2.png)

**Comment by insthync** [comment]
Yes

**Comment by Lbstudio-159** [comment]
thanks

**Comment by insthync** [comment]
I close this, if you still have a new issue, you can open a new issue
