### ISSUE TITLE
Receiving these errors when i am activating ads in services (Unity Ads) 

### ISSUE THREAD

**Issue by pandey623** [suriyun-production/shooter-io-docs#8]
Assets\ShooterIO\Monetization\Scripts\MonetizationManager.cs(12,67): error CS0246: The type or namespace name 'IUnityAdsListener' could not be found (are you missing a using directive or an assembly reference?)
Assets\ShooterIO\Monetization\Scripts\MonetizationManager.cs(197,63): error CS0246: The type or namespace name 'ShowResult' could not be found (are you missing a using directive or an assembly reference?)
Assets\ShooterIO\Monetization\Scripts\MonetizationManager.cs(211,20): error CS0246: The type or namespace name 'ShowResult' could not be found (are you missing a using directive or an assembly reference?)
Assets\ShooterIO\Monetization\Scripts\MonetizationManager.cs(475,57): error CS0246: The type or namespace name 'ShowResult' could not be found (are you missing a using directive or an assembly reference?)

**Comment by insthync** [comment]
Seems like Unity change their Ads package, I might have to update the package follow them

**Comment by insthync** [comment]
You have to import this https://assetstore.unity.com/packages/add-ons/services/unity-monetization-3-3-0-66123

Then in Services, (Find from menu: Window → General → Services) then turn on ADS and `Enable built-in Ads extension`
![Screenshot_181](https://user-images.githubusercontent.com/2697550/69366288-a20d6200-0cc8-11ea-9742-aef6191c2a5d.png)
